algo=input('Digite algo: ')
print('O print primirito desse valor é ', type(algo))
print('Só tem espaços?',algo.isspace())
print('É um numérico?',algo.isnumeric())
print('É alfabético?',algo.isalpha())
print('è alfanumérico?',algo.isalnum())
print('Está em maúsculas?',algo.isupper())
print('Está em minúsculas?',algo.islower())
print('Está capitalizada?',algo.istitle())
